-- =====================================================================
-- Table: users
-- Description: User accounts for the physiotherapy assessment system
-- =====================================================================

CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_users_username ON users(username);

-- Comments
COMMENT ON TABLE users IS 'User accounts for physiotherapy assessment system';
COMMENT ON COLUMN users.username IS 'Unique username for patient identification';
