-- =====================================================================
-- Table: questionnaire_responses
-- Description: KOOS/WOMAC questionnaire responses (10-minute assessment)
-- =====================================================================

CREATE TABLE IF NOT EXISTS questionnaire_responses (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER,
    username VARCHAR(50),

    -- Function questions (f1-f17)
    f1 INTEGER CHECK (f1 BETWEEN 1 AND 4),
    f2 INTEGER CHECK (f2 BETWEEN 1 AND 4),
    f3 INTEGER CHECK (f3 BETWEEN 1 AND 4),
    f4 INTEGER CHECK (f4 BETWEEN 1 AND 4),
    f5 INTEGER CHECK (f5 BETWEEN 1 AND 4),
    f6 INTEGER CHECK (f6 BETWEEN 1 AND 4),
    f7 INTEGER CHECK (f7 BETWEEN 1 AND 4),
    f8 INTEGER CHECK (f8 BETWEEN 1 AND 4),
    f9 INTEGER CHECK (f9 BETWEEN 1 AND 4),
    f10 INTEGER CHECK (f10 BETWEEN 1 AND 4),
    f11 INTEGER CHECK (f11 BETWEEN 1 AND 4),
    f12 INTEGER CHECK (f12 BETWEEN 1 AND 4),
    f13 INTEGER CHECK (f13 BETWEEN 1 AND 4),
    f14 INTEGER CHECK (f14 BETWEEN 1 AND 4),
    f15 INTEGER CHECK (f15 BETWEEN 1 AND 4),
    f16 INTEGER CHECK (f16 BETWEEN 1 AND 4),
    f17 INTEGER CHECK (f17 BETWEEN 1 AND 4),

    -- Pain questions (p1-p9)
    p1 INTEGER CHECK (p1 BETWEEN 1 AND 4),
    p2 INTEGER CHECK (p2 BETWEEN 1 AND 4),
    p3 INTEGER CHECK (p3 BETWEEN 1 AND 4),
    p4 INTEGER CHECK (p4 BETWEEN 1 AND 4),
    p5 INTEGER CHECK (p5 BETWEEN 1 AND 4),
    p6 INTEGER CHECK (p6 BETWEEN 1 AND 4),
    p7 INTEGER CHECK (p7 BETWEEN 1 AND 4),
    p8 INTEGER CHECK (p8 BETWEEN 1 AND 4),
    p9 INTEGER CHECK (p9 BETWEEN 1 AND 4),

    -- Sport/Recreation questions (sp1-sp5)
    sp1 INTEGER CHECK (sp1 BETWEEN 1 AND 4),
    sp2 INTEGER CHECK (sp2 BETWEEN 1 AND 4),
    sp3 INTEGER CHECK (sp3 BETWEEN 1 AND 4),
    sp4 INTEGER CHECK (sp4 BETWEEN 1 AND 4),
    sp5 INTEGER CHECK (sp5 BETWEEN 1 AND 4),

    -- Stiffness questions (st1-st2)
    st1 INTEGER CHECK (st1 BETWEEN 1 AND 4),
    st2 INTEGER CHECK (st2 BETWEEN 1 AND 4),

    -- Symptom questions (s1-s5)
    s1 INTEGER CHECK (s1 BETWEEN 1 AND 4),
    s2 INTEGER CHECK (s2 BETWEEN 1 AND 4),
    s3 INTEGER CHECK (s3 BETWEEN 1 AND 4),
    s4 INTEGER CHECK (s4 BETWEEN 1 AND 4),
    s5 INTEGER CHECK (s5 BETWEEN 1 AND 4),

    -- Quality of Life questions (q1-q4)
    q1 INTEGER CHECK (q1 BETWEEN 1 AND 4),
    q2 INTEGER CHECK (q2 BETWEEN 1 AND 4),
    q3 INTEGER CHECK (q3 BETWEEN 1 AND 4),
    q4 INTEGER CHECK (q4 BETWEEN 1 AND 4),

    -- Flexibility test
    toe_touch_test VARCHAR(10) CHECK (toe_touch_test IN ('can', 'cannot')),

    -- Timestamps
    completed_at TIMESTAMPTZ DEFAULT now(),
    created_at TIMESTAMPTZ DEFAULT now(),

    -- Foreign keys
    CONSTRAINT fk_questionnaire_user_id
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_questionnaire_username
        FOREIGN KEY (username)
        REFERENCES users(username)
        ON DELETE CASCADE
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_questionnaire_user_id ON questionnaire_responses(user_id);
CREATE INDEX IF NOT EXISTS idx_questionnaire_username ON questionnaire_responses(username);
CREATE UNIQUE INDEX IF NOT EXISTS idx_questionnaire_unique_user ON questionnaire_responses(username);

-- Comments
COMMENT ON TABLE questionnaire_responses IS 'KOOS/WOMAC questionnaire responses (10-minute assessment) plus toe touch flexibility test';
COMMENT ON COLUMN questionnaire_responses.toe_touch_test IS 'Can the user touch their toes with straight legs? (can/cannot)';
COMMENT ON COLUMN questionnaire_responses.f1 IS 'Function question 1 (1=no difficulty, 4=extreme difficulty)';
COMMENT ON COLUMN questionnaire_responses.p1 IS 'Pain question 1 (1=none, 4=extreme)';
COMMENT ON COLUMN questionnaire_responses.sp1 IS 'Sport/Recreation question 1 (1=no difficulty, 4=extreme difficulty)';
COMMENT ON COLUMN questionnaire_responses.st1 IS 'Stiffness question 1 (1=none, 4=extreme)';
COMMENT ON COLUMN questionnaire_responses.s1 IS 'Symptom question 1 (1=never, 4=always)';
COMMENT ON COLUMN questionnaire_responses.q1 IS 'Quality of Life question 1 (1=not at all, 4=extremely)';
