-- =====================================================================
-- Table: sts_assessments
-- Description: 30-second Sit-to-Stand test results and biomechanical screening
-- =====================================================================

CREATE TABLE IF NOT EXISTS sts_assessments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER,
    username VARCHAR(50) UNIQUE,

    -- STS Test Results
    repetition_count INTEGER NOT NULL CHECK (repetition_count >= 0),

    -- Biomechanical Assessment
    knee_alignment VARCHAR(10) NOT NULL CHECK (knee_alignment IN ('normal', 'valgus', 'varus')),
    trunk_sway VARCHAR(10) NOT NULL CHECK (trunk_sway IN ('present', 'absent')),
    hip_sway VARCHAR(10) NOT NULL CHECK (hip_sway IN ('present', 'absent')),

    -- Timestamps
    created_at TIMESTAMP DEFAULT now(),
    updated_at TIMESTAMP DEFAULT now(),

    -- Foreign keys
    CONSTRAINT fk_sts_user_id
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_sts_username
        FOREIGN KEY (username)
        REFERENCES users(username)
        ON DELETE CASCADE
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_sts_user_id ON sts_assessments(user_id);
CREATE INDEX IF NOT EXISTS idx_sts_username ON sts_assessments(username);

-- Comments
COMMENT ON TABLE sts_assessments IS '30-second Sit-to-Stand test results with biomechanical screening data';
COMMENT ON COLUMN sts_assessments.repetition_count IS 'Number of sit-to-stand repetitions completed in 30 seconds';
COMMENT ON COLUMN sts_assessments.knee_alignment IS 'Knee alignment observation during STS test (normal/valgus/varus)';
COMMENT ON COLUMN sts_assessments.trunk_sway IS 'Trunk stability during STS test (present/absent)';
COMMENT ON COLUMN sts_assessments.hip_sway IS 'Hip stability during STS test (present/absent)';
