-- =====================================================================
-- Table: exercises
-- Description: Exercise database with positions, muscle recruitment, and difficulty
-- =====================================================================

CREATE TABLE IF NOT EXISTS exercises (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Exercise names
    exercise_name VARCHAR(100) NOT NULL,
    exercise_name_ch VARCHAR(100),

    -- Position flags (boolean)
    position_sl_stand BOOLEAN DEFAULT false,
    position_split_stand BOOLEAN DEFAULT false,
    position_dl_stand BOOLEAN DEFAULT false,
    position_quadruped BOOLEAN DEFAULT false,
    position_supine_lying BOOLEAN DEFAULT false,
    position_side_lying BOOLEAN DEFAULT false,

    -- Muscle recruitment (0-5 scale)
    muscle_quad INTEGER DEFAULT 0 CHECK (muscle_quad BETWEEN 0 AND 5),
    muscle_hamstring INTEGER DEFAULT 0 CHECK (muscle_hamstring BETWEEN 0 AND 5),
    muscle_glute_max INTEGER DEFAULT 0 CHECK (muscle_glute_max BETWEEN 0 AND 5),
    muscle_hip_flexors INTEGER DEFAULT 0 CHECK (muscle_hip_flexors BETWEEN 0 AND 5),
    muscle_glute_med_min INTEGER DEFAULT 0 CHECK (muscle_glute_med_min BETWEEN 0 AND 5),
    muscle_adductors INTEGER DEFAULT 0 CHECK (muscle_adductors BETWEEN 0 AND 5),

    -- Core stability requirements
    core_ipsi BOOLEAN DEFAULT false,
    core_contra BOOLEAN DEFAULT false,

    -- Flexibility requirement (DEPRECATED - use patient data instead)
    toe_touch BOOLEAN DEFAULT false,

    -- Difficulty level
    difficulty_level INTEGER NOT NULL CHECK (difficulty_level BETWEEN 1 AND 10),

    -- Timestamps
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_exercises_difficulty ON exercises(difficulty_level);
CREATE INDEX IF NOT EXISTS idx_exercises_positions ON exercises(position_sl_stand, position_split_stand, position_dl_stand, position_quadruped, position_supine_lying, position_side_lying);

-- Comments
COMMENT ON TABLE exercises IS 'Exercise database with 33 exercises for knee OA rehabilitation';
COMMENT ON COLUMN exercises.exercise_name IS 'Exercise name in English';
COMMENT ON COLUMN exercises.exercise_name_ch IS 'Exercise name in Traditional Chinese (繁體中文)';
COMMENT ON COLUMN exercises.position_sl_stand IS 'Single-leg standing position';
COMMENT ON COLUMN exercises.position_split_stand IS 'Split stance standing position (lunges, step-ups)';
COMMENT ON COLUMN exercises.position_dl_stand IS 'Double-leg standing position (squats)';
COMMENT ON COLUMN exercises.position_quadruped IS 'Four-point kneeling position';
COMMENT ON COLUMN exercises.position_supine_lying IS 'Supine (lying on back) position';
COMMENT ON COLUMN exercises.position_side_lying IS 'Side-lying position';
COMMENT ON COLUMN exercises.muscle_quad IS 'Quadriceps recruitment (0-5 scale, 0=none, 5=maximal)';
COMMENT ON COLUMN exercises.muscle_hamstring IS 'Hamstring recruitment (0-5 scale)';
COMMENT ON COLUMN exercises.muscle_glute_max IS 'Gluteus maximus recruitment (0-5 scale)';
COMMENT ON COLUMN exercises.muscle_hip_flexors IS 'Hip flexor recruitment (0-5 scale)';
COMMENT ON COLUMN exercises.muscle_glute_med_min IS 'Gluteus medius/minimus recruitment (0-5 scale) - targets valgus alignment';
COMMENT ON COLUMN exercises.muscle_adductors IS 'Hip adductor recruitment (0-5 scale) - targets varus alignment';
COMMENT ON COLUMN exercises.core_ipsi IS 'Requires ipsilateral core stability (contralateral limb movement)';
COMMENT ON COLUMN exercises.core_contra IS 'DEPRECATED - Not used in current algorithm';
COMMENT ON COLUMN exercises.toe_touch IS 'DEPRECATED - Use patient toe_touch_test instead';
COMMENT ON COLUMN exercises.difficulty_level IS 'Exercise difficulty (1=easiest, 10=hardest)';
